### ISSUE TITLE
Need to change XmlAttribute "lang" to "xml:lang" in LyricLanguage.java

### ISSUE THREAD

**Issue by Koldunstvo** [Audiveris/proxymusic#2]
According to [this documentation](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-lyric-language.htm), 3rd attribute must be called "xml:lang", not "lang":
![image](https://user-images.githubusercontent.com/64807782/82590947-405e7f80-9ba7-11ea-92b4-042467e83c54.png)

**Comment by hbitteur** [comment]
@Koldunstvo 
The Java source is automatically generated from MusicXML schema (musicxml.xsd).
Do you know how we can fix this?

The fix should apply to all instances of xml:lang, that is in AccidentalText, Attributes, FormattedText, FormattedTextId, LyricLanguage and TextElementData

By the way, a similar fix should apply to xml:space as well in AccidentalText, FormattedText and FormattedTextId

Please help me!

**Comment by PeterGreth** [comment]
Are you sure the name is supposed to be `xml:lang` at this location? From what I understand from [this thread](https://stackoverflow.com/questions/3006373/jaxb-unable-to-handle-attribute-with-colon-in-name), the `xml:` prefix is a namespace. As you can see in the image above the namespace is already defined :)

**Comment by hbitteur** [comment]
I just added a lyric-language element in the dummy score-partwise test, and I got this in the produced xml file:

```
<defaults>
    <lyric-language xml:lang="fr"></lyric-language>
  </defaults>
```

My understanding is that the output complies with MusicXML spec
So there is nothing to "fix", the outputs are OK.

**Comment by hbitteur** [comment]
And I have wasted a couple of hours fighting with JAXB binding customizations documentation for just nothing :-( :-(
Closing this (false) issue
